### ISSUE TITLE
add icon support

### ISSUE THREAD

**Issue by nkappler** [nkappler/ctxmenu#12]
if we want selectable items (i.e. checkboxes), how would they handle icons?

**Comment by musicman3** [comment]
My icon solution for Bootstrap 5 and Bootstrap Icons:
```

/* any menu item that has a submenu */
.ctxmenu li.submenu::after{
    content:'\bi-caret-right';
    position:absolute;
    display:block;
    top:0;
    right:0.3em;
    font-family:bootstrap-icons;
    line-height:22px;
}

```

**Comment by musicman3** [comment]
Our layout designer has done everything smoothly and beautifully now. Here is a screen: 
![1](https://user-images.githubusercontent.com/36889207/106757434-02bc5c80-6639-11eb-8640-59a408c3f157.png)

**Comment by nkappler** [comment]
Thanks for the detailed information. I thought the "off-the-screen" issue was handled, but maybe it only works for the horizontal direction... I've created another issue to track this #14

**Comment by musicman3** [comment]
The off-screen problem occurs on the sub menu. At level 1, everything is fine.

**Comment by nkappler** [comment]
submenus can also switch direction and appear to the left when they reach the end of the screen, see the demo at https://nkappler.de/ctxmenu/ open context menu and select "even more actions".
I though the y coordinate was also working

**Comment by musicman3** [comment]
You only have a horizontal submenu in the demo. I have it horizontally and down. There are many lines down.
