### ISSUE TITLE
submenu can be off screen

### ISSUE THREAD

**Issue by nkappler** [nkappler/ctxmenu#14]
see #12

**Comment by musicman3** [comment]
The problem still remains. I tried the fix #14 but it doesn't fix the problem

**Comment by nkappler** [comment]
The changes are not on master branch yet, make sure you download from the 1.2 branch:
https://raw.githubusercontent.com/nkappler/ctxmenu/1.2/standalone/ctxmenu.js

Also, if you use images in your menu (I guess you do with the icons)
Make sure they are preloaded to the cache. Otherwise the size calculation happens before the image load and the menu ends up larger than it thinks.

Close your devtools, if you use the "disable cache" option.

This should do the trick hopefully.
Making the size calculation handle uncached images is more work, which I postponed for now

**Comment by musicman3** [comment]
There are still problems. In the lower right part of the screen, if you open the menu 2 times in a row, a bug appears a second time. The first time goes well.

**Comment by musicman3** [comment]
Our layout designer said that it is very wrong to embed css settings in a js file. Some styles overlap each other. Therefore, you need to keep everything separate.

**Comment by nkappler** [comment]
thanks for the hint, I fixed the issue.

Having some css properties in the code is intentional, otherwise I would need to make another request and load a second file, which I don't want. I want to keep it simple and fast.
The generated css is added as the first style sheet to the DOM, so overriding is very easy, as the included css rules have the least possible priority. This is done so you can restyle it easily. There should be nothing overlapping, are you facing problems?

Possible Future themes will be handled as css files though, as they would increase the file size otherwise and they are not needed by everyone.

**Comment by musicman3** [comment]
Yes, the menu functions well now.

**Comment by musicman3** [comment]
P.S. I found you have a new undocumented method that allows you to close the menu. It worked for me. 
`ctxmenu.closeMenu();`

**Comment by musicman3** [comment]
With the latest changes, the problem of moving the menu off the edges of the screen returned.

**Comment by nkappler** [comment]
closeMenu is a private method as you should not nees to do this... I thought i fixed it already 😅

**Comment by musicman3** [comment]
Yes, everything has already been fixed. I wrote this before it was fixed

**Comment by nkappler** [comment]
ok, great to hear 👍
