### ISSUE TITLE
Get the target element

### ISSUE THREAD

**Issue by smalos** [nkappler/ctxmenu#19]
In the callback beforeRender I can get the current target with event.currentTarget.
Is there an elegant way to retrieve it when a "Action Item" is clicked?

**Comment by nkappler** [comment]
yes, the action callback receives the event as parameter, so it should look something like this:

```typescript
const callback = (e: MouseEvent) => {
    const currentTarget = e.currentTarget;
}
```

**Comment by nkappler** [comment]
I wasn't aware that the documentation was missing this,
I've added it now. Thanks for your question! 💯
