### ISSUE TITLE
Add user-select: none

### ISSUE THREAD

**Issue by smalos** [nkappler/ctxmenu#20]
What about adding  user-select: none to ctxmenu li?
```
".ctxmenu li": {
	margin: "1px 0",
	display: "block",
	position: "relative",
	"-moz-user-select": "none",
	"-webkit-user-select": "none",
	"-ms-user-select": "none",
	"user-select": "none"
},
```

**Comment by nkappler** [comment]
good idea!
If you can make a PR, I will be happy to merge it

**Comment by smalos** [comment]
I created a PR for ctxmenu.js . Not sure how the .ts and .min versions are created.

**Comment by nkappler** [comment]
> Not sure how the .ts and .min versions are created.

Should be `npm run build`
