### ISSUE TITLE
closeMenu method documentation

### ISSUE THREAD

**Issue by smalos** [nkappler/ctxmenu#22]
Add documentation for the closeMenu method:

E.g. The closeMenu method is used to close an open context menu.

**Comment by nkappler** [comment]
The closeMenu method is not intended to be part of the public API, it is an internal method right now.
Do you have a specific need for it and can describe the use case in more detail?

Thank you

**Comment by smalos** [comment]
The menu doesn't close when the parent element (e.g. document body) is clicked.
Since ev.target.parentElement is null, closeMenu() is not called.
My workaround is to use another, already existing listener that calls closeMenu().

```
    window.addEventListener("click", function (ev) {
      var item = ev.target && ev.target.parentElement;

      if (item && item.className !== "interactive") {
        _this.closeMenu();
      }
    });
```

**Comment by nkappler** [comment]
This sounds like a bug.
Do you have an example (webiste or codesandbox) for this?

**Comment by nkappler** [comment]
in which browser did you observe this?
parentElement of document body should be `html` and not `null`

![image](https://user-images.githubusercontent.com/9429273/129695366-bed600f1-360d-4548-b180-b6ad221da3db.png)

**Comment by smalos** [comment]
When I run this JS in the developer console while the menu is open, 
`document.getElementsByClassName("ctxmenu")[0].parentNode`
or jQuery notation `$('.ctxmenu').parent()`

I get this back:
`<body id=​"nubody" onload=​"nuLoad()​" onresize=​"nuResize()​" class=​"nuEditBody" title=​"ID:​ nubody" style=​"transform:​ scale(1)​;​ width:​ 100%;​ height:​ 185px;​">​…​</body>​`

Only  the parent of the parent will be `html`

`$('.ctxmenu').parent().parent()`

You can check out demo.nubuilder.com and right-click any button.

**Comment by nkappler** [comment]
I think I know whats going on:
Your body element doesn't cover the whole viewport:
![grafik](https://user-images.githubusercontent.com/9429273/130075083-43bafb5a-3288-4e43-a3d5-fb11d2a779b7.png)

This is probably why the event's target is `html` when it usually is `body`.
I'll add a check if the target is `html` as well.

Thanks for reporting this 💯
