### ISSUE TITLE
Do not close menu on scroll

### ISSUE THREAD

**Issue by smalos** [nkappler/ctxmenu#28]
If the menu is too large or the screen too small, you sometimes have to scroll to see the whole menu. However, the menu is closed when you scroll.
How about adding an option to disable the "scroll" addEventListener?

**Comment by nkappler** [comment]
Thanks for your bug report 💯 
Sounds like it should be easy to fix by checking if the scroll target ist part of the menu, However I won't be able to fix it until next week...
Feel free to open a PR if it's urgent 😊
