### ISSUE TITLE
Position Calculation is wrong when body has css transform

### ISSUE THREAD

**Issue by smalos** [nkappler/ctxmenu#31]
The x,y positions are not calculated correctly when the element is outside the visible area (scrollbar is active)

Check out:
https://test.nubuilder.cloud/index.php?u=test&p=nutest&f=618b6d9e9485c80

It must have to do something with scrollHeight, offsetHeight, clientHeight but I'm not sure how to address this issue.
https://javascript.info/size-and-scroll-window

**Comment by nkappler** [comment]
Thanks for reporting, it seems like the window scroll offsets are not included in the clientY values of events.

**Comment by nkappler** [comment]
I tried to reproduce it with my setup but everything worked fine.
I had a fix in mind, namely switching from `clientX/clientY` to `pageX/pageY` which seemed to produce the right result for your usecase.
However this broke my setup and the menu was now in the wrong place for me, so I've looked at your demo page again.

It seems like the `transform: scale(1)` css on your `body` element messes things up, if I disable this rule, it works fine.

Is it possible for you to remove this line for a quick fix? I need to investigate further how to resolve this.

![image](https://user-images.githubusercontent.com/9429273/141294572-b5ac6d92-cad9-42cc-88b1-cac24a6961c4.png)

**Comment by smalos** [comment]
I'm afraid that it's not an option to remove transform: scale(1). There are other places in code where a variable scale factor is used. That's why I would be happy if another fix could be implemented.

**Comment by nkappler** [comment]
What about introducing another wrapper `div` as a child of  `body` where you render everything and apply the  `scale` to this div, this shouldn't interfere with the menu since it is rendered as a direct child of `body`...

If this is not an option either, please let me know. I'll fix this eventually but it is a tricky problem 😄
I am just trying to get you a workaround quickly 🙂

**Comment by nkappler** [comment]
Hi @smalos,
I've just published version 1.4.1, which should fix the issue.
I tried to reproduce your setup as closely as possible. Please let me know if you still experience any issues! 😊

**Comment by smalos** [comment]
Thank you so much @nkappler ! The new version works like a charm.
