### ISSUE TITLE
Size calculation wrong when body has a scrollbar and menu would overflow

### ISSUE THREAD

**Issue by nkappler** [nkappler/ctxmenu#34]
![image](https://user-images.githubusercontent.com/9429273/143065503-068a8ddd-7ff3-4118-b42c-9a8748bf471c.png)

It seems like the scrollbar is not taken into account, causing long items to wrap, which means the menu ends up larger than expected, potentially getting cropped at the bottom.

**Comment by smalos** [comment]
I noticed that too. Would be nice if you find a fix soon. Thanks!
