### ISSUE TITLE
Suggestion: Change divider color

### ISSUE THREAD

**Issue by smalos** [nkappler/ctxmenu#37]
How about changing #aaa to #dadce0  ? Chrome uses the same color in its context menu. IMO it looks more decent than the darker greyish color.

```
 .ctxmenu li.divider {
	border-bottom: 1px solid #dadce0 ;
}
```

**Comment by smalos** [comment]
And use the same color for the border:

```
.ctxmenu {
    border: 1px solid #dadce0 ;
}
```

**Comment by nkappler** [comment]
The goal of this library was never to look like the native context menus, which by the way depends on many things, like which browser you are using, browser color theme, the operating system, or whether dark mode or high contrast is enabled on your system.

Personally, I find `#dadce0` provides too little contrast, but you can easily customize it by adding a little css to your page:
><sup>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&uarr;  I love how GitHub puts a little color indicator when you escape it 😄</sup>

```html
<style>
  .ctxmenu,
  .ctxmenu li.divider {
    border-color: #dadce0;
  }
</style>
```

I've created a small example [codesandbox](https://codesandbox.io/s/ctxmenu-border-color-52hji3?file=/index.html).

**Comment by nkappler** [comment]
I was thinking about providing more themes out of the box, as currently there's only the `docs/darkTheme.css` file.
I would be happy to merge a PR if you want to write a new theme that's closer to the system UI.
I`d suggest to move the themes to a new folder in the root directory.

**Comment by smalos** [comment]
The standard theme looks pretty much similar to chrome's context menu, IMO it doesn't need much tweaking.
I retrieved all divider colors of the major browsers  and ordered them by lightness.
#AAA is by far the darkest color. I had already customized my css but of course I will leave it up to you if you want to keep the darker grey color.

![colors_sorted](https://user-images.githubusercontent.com/45562597/174942744-388dc0ea-fa00-4840-9d6a-ee1c9c34d06d.png)

```
ctxmenu: 
#AAA
170,170,170

Firefox:
207,207,216
#CFCFD8

Chrome:
218,220,224
#DADCE0

Edge:
218,218,218
#DADADA

IE:
215,215,215
#D7D7D7
```

**Comment by nkappler** [comment]
thanks for the research, I'll think about it.
