### ISSUE TITLE
Error on postinstall script in published version

### ISSUE THREAD

**Issue by jkorrek** [nkappler/ctxmenu#38]
The postinstall script introduced by https://github.com/nkappler/ctxmenu/commit/bdc40a20d1003faaca37af4aa2359e511f88c3ea will cause errors when installing version 1.4.4 into any project, as the `util/convertStyles.js` file is missing in the published package.

I assume the postinstall script is only required when running / building ctxmenu, but not when installing it as a dependency?

**Comment by nkappler** [comment]
bummer, I had thought about whether this would become a problem but forgot to test it... 😨

**Comment by nkappler** [comment]
Thanks @jkorrek
