### ISSUE TITLE
Menu is opened at the wrong position when Enter key is pressed

### ISSUE THREAD

**Issue by smalos** [nkappler/ctxmenu#41]
In your demo (index.html), if you set the focus on the "Click this button" button (without clicking it) and hit Enter, the menu is opened at a wrong position.
Maybe check if a key is pressed and then use event.target to determine the source element.

**Comment by nkappler** [comment]
Thanks for reporting, I'm on it.
It seems like we didn't get the position calculation based on elements quite right in the position update, so it might be a bit more complicated. (event based position calculation works fine though)
If you have this issue yourself, you could probably fix it in the meantime by adding a keypress handler and opening the menu manually...

**Comment by smalos** [comment]
Well, I don't open the menu by mouse position myself but I thought  I report it anyway.

**Comment by smalos** [comment]
Let's close this for now. I will let you to decide whether to fix it or not,
