### ISSUE TITLE
Access parent menu selected target

### ISSUE THREAD

**Issue by max-rh** [nkappler/ctxmenu#44]
Hi there,

Thanks for the great context menu library, finally a flexible library.

I have one request, is there a way to access the parent menu selected Item ?

I have a scenario where i have multiple sub-menues but once the item in the last sub-menu is selected i need the callback function in it to access the targets from the parent menus that caused the sub-menues to open.

is there a way to achieve that ? cause i noticed that the target object right now doesn't include information about the parent menu item that opened this submenu

**Comment by nkappler** [comment]
Hi Max,

every submenu is a direct ChildElement of the parent list item that it belongs to.
Here's an example of the generated DOM:
```html 
<ul class="ctxmenu" style="position: fixed; left: 646px; top: 493px;">
  <li title="" class="interactive"><span>Add marker</span></li>
  <li title="" class="interactive"><span>Delete all markers</span></li>
  <li title="" class="interactive submenu">
    <span>Go to marker</span>
    <ul class="ctxmenu" style="position: fixed; left: 501.406px; top: 539px;">
      <li title="" class="interactive"><span>"New Marker"</span></li>
    </ul>
  </li>
</ul>
```

This means that while there is no dedicated API for this, you can achieve this via the DOM:

```html
<body id="body" style="width: 100vh; height: 100vh;">
    <script>
        ctxmenu.attach("#body", [
            {
                text: "Parent",
                subMenu: [
                    {
                        text: "child",
                        action: (event) => {
                            const childListElement = event.target.parentElement;
                            const submenu = childListElement.parentElement;
                            const parentListElement = submenu.parentElement;
                            console.log(parentListElement);
                        }
                    }
                ]
            }
        ])
    </script>
</body>
```

Note that a default menu item has an extra span to wrap the text, hence the extra `.parentElement` after `event.target`.

You might need to modify this example a bit, depending on which type of item you are tryign to achieve this, but it is totally doable 😊
Please let me know if you need further assistance.

Happy Coding
- Nikolaj

**Comment by nkappler** [comment]
Hi Max,

`parentListItem.firstChild.innerText` should work reliably, however if you want to be extra sure, I'd suggest going with a [Query Selector](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector):

```javascript
parentListItem.querySelector("span").innerText
```

**Comment by max-rh** [comment]
Thanks @nkappler  , this works perfectly. 

While on the subject of parent menus, is there a way to get a callback function not on "select" but on "hover" or "mouseenter" event; i mean obviously the mouseenter event opens the sub-menu, but could I pass extra functionality besides this.

I am closing this issue since its solved, thanks alot. lemme know if its ok to open another one for the mouseenter event if its doable :)

**Comment by nkappler** [comment]
That's a very good question actually...

I was expecting this modified example to do what you want:
```javascript
ctxmenu.attach("#body", [
            {
                text: "Parent",
                subMenu: function beforeOpenSubMenu() {
                    alert("beforeOpenSubmenu");

                    return [
                        {
                            text: "child",
                            action: (event) => {
                                const childListElement = event.target.parentElement;
                                const submenu = childListElement.parentElement;
                                const parentListElement = submenu.parentElement;
                                console.log(parentListElement.querySelector("span").innerText);
                            }
                        }
                    ];
                }
            }
        ], function beforeOpen(menu) {
            alert("BeforeOpen")

            return menu;
        });
```

You can pass a function as a third parameter to the `attach` method, which will be called before the root menu opens.
Note that the function receives the menu definition as a parameter and also has to return it.
You can modify it as you please, but this function needs to return a valid menu definition.

As per [my own documentation](https://github.com/nkappler/ctxmenu#submenu-item), you should also be able to pass a function to generate the submenu (`beforeOpenSubMenu`), however the `Parent` list item ends up being disabled.
It's been a while that I wrote this code and honestly the test coverage is at best mediocre, since it depends on manual testing,
but I am pretty sure that this is a bug.

The `beforeOpenSubMenu` should be called just before the submenu is being opened, but currently it is never called.
I've created a new bug #45 to track this.

**Comment by nkappler** [comment]
I have just released a patch to npm, so if you have installed it via npm, the above example should now work as expected, too.
Please let me know if you have any further questions 😊

**Comment by max-rh** [comment]
Thanks @nkappler ,
I am using this in a frontend page, so I'll download the new library and test it.

but just wondering if it could be just as simple as the "action" attribute atleast for items that do not have a sub-menu, so basically before the user clicks on an item to execute the callback, I could call a function on mouseenter.

and I am spawning the context menu manually using .show, since I have a dashboard and i dont need to attach it to any specific element

**Comment by nkappler** [comment]
I see...
That feature would require a little more effort I think.
May I ask what you are trying to achieve with the mouseenter event? Maybe there's another way to achieve the same result 😊

Also I am happy to review any Pull Request or if you are patient and explain your usecase in more detail, I'll have a go myself...

**Comment by max-rh** [comment]
Sure, so I have a KonvaJS dashboard; now until i found this context menu library, i used to build my own menus to allow the user to interact with the dashboard; adding elements, modifying or deleting.

now the cool thing about mouseenter events is mainly with delete functionalities; if a user opened a context-menu and hovers over the delete item, i highlight and blink certain elements to show what will get deleted if the selected item is deleted, now once its clicked, a popup shows to confirm the deletion, but that blinking animation prior to deleting is what i had using my manual menus and its what i am trying to achieve here.

I didnt get the chance to go deep in the ctxmenu code, but I would be happy to open a PR if i get the chance to review it.

Thanks :)

**Comment by nkappler** [comment]
I've created another Issue to track this feature request and keep this issue clean, since I've pinned it.
