### ISSUE TITLE
Microsoft Defender detects it as virus

### ISSUE THREAD

**Issue by smalos** [nkappler/ctxmenu#53]
Are you also experiencing an issue where, upon downloading the zip file of the latest release, Windows Defender flags it as dangerous, citing "This program executes commands from an attacker" and the file gets deleted?

**Comment by nkappler** [comment]
To be honest I don't think that I've ever donwloaded the zip files, which by the way are automatically generated by github and not by me.

ctxmenu is a single-file browser plugin, so you can just download that from the repo's root, or from the website.
Another possibility is to download the latest version from unpkg.com or embed it directly from there, like I do on my demo page:
```html
<script src="https://unpkg.com/ctxmenu/index.min.js" type="module"></script>
```

**Comment by nkappler** [comment]
Have you downloaded the zip from the releases section or from npm?

**Comment by smalos** [comment]
Downloaded from the release section:

https://github.com/nkappler/ctxmenu/releases/tag/v1.7.0
