### ISSUE TITLE
Adding context menu to multiple elements

### ISSUE THREAD

**Issue by aderchox** [nkappler/ctxmenu#55]
Hi, thanks for the library. I have a question.
Say one wants the context menu to appear when elements that have a certain similar class are clicked, eg, certain table cells.
Currently, using a class target (eg, `.target`), only attaches the context menu to the first match it finds.

**Comment by nkappler** [comment]
Hi @aderchox,
thanks for the feedback. This is working as designed. However I can see that this would be a useful feature.

Have you tried to attach the context menu to the table itself? In the [onBeforeShow](https://github.com/nkappler/ctxmenu?tab=readme-ov-file#ctxconfig) method you could then update the menu based on the table cell event target.

Let me know if this works for you.

**Comment by aderchox** [comment]
Thanks, yes, this works for my current need. I should see if it does the job in upcoming needs too. I only wish that passing an empty array as definition resulted in the normal context menu (ie, the non-ctxmenu one). Then I could use it in `onBeforeShow` to not show the custom context menu on points that mouse coordinates are not on a table cell (There are gaps between them). Currently, I'm returning a dummy text only context menu. But all in all, this solution does the job for now. I understand that this is supposed to be a tiny and simple library and it's great in what it does. Thanks for the kind support.

**Comment by nkappler** [comment]
Please let me know if you are facing any other issues and feel free to re-open
